/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LegacySequenceBridge */

#ifndef _Included_LegacySequenceBridge
#define _Included_LegacySequenceBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     LegacySequenceBridge
 * Method:    compute
 * Signature: (IDLCombinator;)D
 */
JNIEXPORT jdouble JNICALL Java_LegacySequenceBridge_compute
  (JNIEnv *, jobject, jint, jdouble, jobject);

#ifdef __cplusplus
}
#endif
#endif
